name: CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get .

      - name: Execute Test
        run: go test ./... -cover

  Build_Push_Image:
    needs: Unit_Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-helm:${{ github.run_number }}
