name: CD Pipeline

on:
  push:
    branches: ['main']

jobs:
#  Unit_Tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Cloning Repository
#        uses: actions/checkout@v4
#
#      - name: Setup Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: '1.22'
#
#      - name: Install dependencies
#        run: go get .
#
#      - name: Execute Test
#        run: go test ./... -cover
#
#  Build_Push_Image:
#    needs: Unit_Tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Cloning Repository
#        uses: actions/checkout@v4
#
#      - name: Login To Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Set up Docker Build
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: .docker/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-helm:${{ github.run_number }}

  Build_Chart:
    #needs: Build_Push_Image
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.4

      - name: List .docker/api-helm directory
        run: ls -la .docker/api-helm

      - name: Build Helm Char
        run: helm package .docker/api-helm/ . --app-version ${{ github.run_number }}

      - name: List contents including .docker
        run: ls -la
#
#      - name: Clone Chars Repo
#        run: |
#          git clone https://github.com/ygsanabria8/api-helm-activity.charts.git |
#          && mv api-helm-activity/api-helm-1.1.0.tgz api-helm-activity.charts |
#          git add . && git commit "new version helm ${{ github.run_number }}" |
#          git push origin main
