name: CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  Unit_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get .

      - name: Execute Test
        run: go test ./... -cover

  Build_Push_Image:
    needs: Unit_Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-helm:${{ github.run_number }}

  Build_Chart:
    needs: Build_Push_Image
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.4

      - name: Build Helm Char
        run: helm package .docker/api-helm/ --app-version ${{ github.run_number }}

      - name: Extract Helm package
        run: tar -xzvf *.tgz

      - name: Cloning Chart Repo
        run: git clone https://ygsanabria8:${{ secrets.GH_TOKEN }}@github.com/ygsanabria8/api-helm-activity.charts charts

      - name: Replace Api Helm Files
        run: |
          cd charts
          rm -rf api-helm
          mv ../api-helm .

      - name: Setup GitHub credentials
        run: |
          cd charts
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Upload Changes Into Chart Repo
        run: |
          cd charts
          git add .
          git commit -m "Upgrade Api Helm Version To: ${{ github.run_number }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}